# Generated by Django 3.2.13 on 2022-08-24 11:13

import articles.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20220824_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='', upload_to=articles.models.namer),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 24, 11, 13, 25, 373703, tzinfo=utc)),
        ),
    ]
