# Generated by Django 3.2.13 on 2022-08-24 11:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20220824_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='introduction',
            field=models.TextField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 24, 11, 23, 5, 280606, tzinfo=utc)),
        ),
    ]
